# Generated by Django 4.2 on 2025-06-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0002_order_business_name_order_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preserved_cart_data',
            field=models.TextField(blank=True, help_text='JSON data of cart contents for payment retry', null=True),
        ),
    ]
