# Generated by Django 5.0.14 on 2025-10-12 15:56

import django.db.models.deletion
import pyuploadcare.dj.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0003_order_preserved_cart_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Recipe Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe name/title', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Recipe introduction/description')),
                ('ingredients', models.JSONField(default=list, help_text='List of ingredients with quantities (JSON format)')),
                ('instructions', models.JSONField(default=list, help_text='Step-by-step cooking instructions (JSON format)')),
                ('prep_time_minutes', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('cook_time_minutes', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('servings', models.PositiveIntegerField(help_text='Number of servings/yield')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Upload recipe image')),
                ('price', models.DecimalField(decimal_places=2, default=100.0, help_text='Price in Kenyan Shillings (KES)', max_digits=10)),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file of the complete recipe', null=True, upload_to='recipes/pdfs/%Y/%m/%d')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'healthy, quick, protein-rich')", max_length=200)),
                ('is_published', models.BooleanField(default=True, help_text='Recipe visibility status')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured recipe')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('preview_content', models.TextField(blank=True, help_text='Free preview content for non-purchased users')),
                ('related_products', models.ManyToManyField(blank=True, help_text='YummyTummy products that complement this recipe', to='yummytummy_store.product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='yummytummy_store.recipecategory')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RecipePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yummytummy_store.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummytummy_store.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['id', 'slug'], name='yummytummy__id_4e0b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='yummytummy__title_787474_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created'], name='yummytummy__created_5136e3_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_published'], name='yummytummy__is_publ_6d3185_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipepurchase',
            unique_together={('user', 'recipe')},
        ),
    ]
