# Generated by Django 5.2.17 on 2026-09-04 11:30

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def clean_legacy_catalog_and_order_items(apps, schema_editor):
    Ingredient = apps.get_model('yummytummy_store', 'Ingredient')
    ProductIngredient = apps.get_model('yummytummy_store', 'ProductIngredient')
    ProductVariant = apps.get_model('yummytummy_store', 'ProductVariant')
    OrderItem = apps.get_model('yummytummy_store', 'OrderItem')

    canonical_ingredients = {}
    for ingredient in Ingredient.objects.order_by('pk').iterator():
        key = (ingredient.name or '').casefold()
        canonical = canonical_ingredients.get(key)
        if canonical is None:
            canonical_ingredients[key] = ingredient
            continue

        for relation in ProductIngredient.objects.filter(ingredient=ingredient).iterator():
            existing = ProductIngredient.objects.filter(
                product_id=relation.product_id,
                ingredient=canonical,
            ).first()
            if existing:
                if existing.percentage is None and relation.percentage is not None:
                    existing.percentage = relation.percentage
                    existing.save(update_fields=['percentage'])
                relation.delete()
            else:
                relation.ingredient = canonical
                relation.save(update_fields=['ingredient'])
        ingredient.delete()

    seen_product_ingredients = set()
    for relation in ProductIngredient.objects.order_by('pk').iterator():
        key = (relation.product_id, relation.ingredient_id)
        if key in seen_product_ingredients:
            relation.delete()
            continue
        seen_product_ingredients.add(key)
        if relation.percentage is not None:
            relation.percentage = min(max(relation.percentage, Decimal('0.00')), Decimal('100.00'))
            relation.save(update_fields=['percentage'])

    canonical_variants = {}
    for variant in ProductVariant.objects.order_by('pk').iterator():
        key = (variant.product_id, variant.name)
        canonical = canonical_variants.get(key)
        if canonical is None:
            canonical_variants[key] = variant
        else:
            OrderItem.objects.filter(variant=variant).update(variant=canonical)
            variant.delete()

    for variant in ProductVariant.objects.filter(additional_price__lt=0).iterator():
        variant.additional_price = Decimal('0.00')
        variant.save(update_fields=['additional_price'])

    for item in OrderItem.objects.select_related('product', 'variant').iterator():
        fields = []
        if not item.product_name:
            item.product_name = item.product.name
            fields.append('product_name')
        if item.variant_id and not item.variant_name:
            item.variant_name = item.variant.name
            fields.append('variant_name')
        if item.price < 0:
            item.price = Decimal('0.00')
            fields.append('price')
        if item.quantity < 1:
            item.quantity = 1
            fields.append('quantity')
        if fields:
            item.save(update_fields=fields)


def backfill_payment_ledger(apps, schema_editor):
    Order = apps.get_model('yummytummy_store', 'Order')
    Payment = apps.get_model('yummytummy_store', 'Payment')
    PaymentAttempt = apps.get_model('yummytummy_store', 'PaymentAttempt')

    status_map = {
        'completed': 'succeeded',
        'refunded': 'refunded',
        'processing': 'processing',
        'failed': 'failed',
        'pending': 'pending',
    }
    seen_checkout_ids = set()
    for order in Order.objects.order_by('pk').iterator():
        payment_status = status_map.get(order.payment_status, 'pending')
        payment = Payment.objects.create(
            order=order,
            method=order.payment_method,
            status=payment_status,
            amount=max(order.total_amount or Decimal('0.00'), Decimal('0.00')),
            provider_reference=order.mpesa_receipt_number or order.transaction_id or '',
            is_current=True,
            completed_at=(
                order.mpesa_transaction_date or order.created
                if payment_status in {'succeeded', 'refunded'}
                else None
            ),
        )

        checkout_id = order.mpesa_checkout_request_id or ''
        if not checkout_id or checkout_id in seen_checkout_ids:
            continue
        seen_checkout_ids.add(checkout_id)
        attempt = PaymentAttempt.objects.create(
            payment=payment,
            sequence=1,
            status=(
                'succeeded' if payment_status in {'succeeded', 'refunded'}
                else 'failed' if payment_status == 'failed'
                else 'processing'
            ),
            checkout_request_id=checkout_id,
            merchant_request_id=order.mpesa_merchant_request_id or '',
            completed_at=(
                order.mpesa_transaction_date or order.created
                if payment_status in {'succeeded', 'refunded', 'failed'}
                else None
            ),
        )
        PaymentAttempt.objects.filter(pk=attempt.pk).update(initiated_at=order.created)


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0005_add_whatsapp_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('whatsapp', 'WhatsApp Order'), ('offline', 'Offline / Manual Order'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_current', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mpesa', max_length=32)),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('event_type', models.CharField(default='stk_callback', max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload_hash', models.CharField(max_length=64)),
                ('redacted_payload', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=16)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product__name', 'name']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product name captured when the order was placed.', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Variant name captured when the order was placed.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available base-product units. Variant stock is managed per variant.'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='Prevent ordering when the available stock reaches zero.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Optional internal stock code.', max_length=64),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available units when inventory tracking is enabled on the product.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='For percentage type: enter percentage value (e.g., 10 for 10%). For fixed amount type: enter amount in Kenyan Shillings (KES)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount in Kenyan Shillings (KES)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('whatsapp', 'WhatsApp Order'), ('offline', 'Offline / Manual Order'), ('cash_on_delivery', 'Cash on Delivery')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price captured when the order was placed, in KES.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='yummytummy_store.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='yummytummy_store.productvariant'),
        ),
        migrations.AlterField(
            model_name='ordertrackingstatus',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('offline_order_created', 'Offline Order Created'), ('processing', 'Processing'), ('packaging', 'Packaging'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price in Kenyan Shillings (KES).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Include the unit, for example 800 g or 500 ml.', max_length=50),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount added to the base product price.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Recipe visibility status'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Price in Kenyan Shillings (KES)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(clean_legacy_catalog_and_order_items, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_ingredient_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='order_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_ingredient_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), models.Q(('percentage__gte', 0), ('percentage__lte', 100)), _connector='OR'), name='ingredient_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('additional_price__gte', 0)), name='variant_additional_price_nonnegative'),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='yummytummy_store.order'),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='tracking_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='yummytummy_store.ordertrackingstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='yummytummy_store.order'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='yummytummy_store.payment'),
        ),
        migrations.AddField(
            model_name='paymentproviderevent',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='yummytummy_store.paymentattempt'),
        ),
        migrations.AddField(
            model_name='paymentproviderevent',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='yummytummy_store.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='yummytummy_store.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_payment_ledger, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'created_at'], name='yummytummy__status_e17cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status', '-created_at'], name='yummytummy__method_c64a43_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('order',), name='one_current_payment_per_order'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('payment', 'sequence'), name='unique_payment_attempt_sequence'),
        ),
        migrations.AddIndex(
            model_name='paymentproviderevent',
            index=models.Index(fields=['provider', 'processing_status', '-received_at'], name='yummytummy__provide_42076f_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
