# Generated by Django 5.2.17 on 2026-09-04 11:46

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0006_notificationoutbox_payment_paymentattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, help_text='Upload product image', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, help_text='Upload recipe image', null=True),
        ),
    ]
