# Generated by Django 4.2 on 2025-05-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0006_alter_order_city_alter_order_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='For percentage type: enter percentage value (e.g., 10 for 10%). For fixed amount type: enter amount in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, help_text='Discount amount in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal amount in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Kenyan Shillings (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Kenyan Shillings (KES)', max_digits=10),
        ),
    ]
