# Generated by Django 5.2.17 on 2026-09-04 11:48

from django.db import migrations, models


def clear_duplicate_provider_references(apps, schema_editor):
    Payment = apps.get_model('yummytummy_store', 'Payment')
    duplicates = (
        Payment.objects.exclude(provider_reference='')
        .values('method', 'provider_reference')
        .annotate(reference_count=models.Count('pk'))
        .filter(reference_count__gt=1)
    )
    for duplicate in duplicates.iterator():
        payments = Payment.objects.filter(
            method=duplicate['method'],
            provider_reference=duplicate['provider_reference'],
        ).order_by(
            models.Case(
                models.When(status__in=['succeeded', 'partially_refunded', 'refunded'], then=0),
                default=1,
                output_field=models.IntegerField(),
            ),
            'created_at',
            'pk',
        )
        for payment in payments[1:]:
            payment.provider_reference = ''
            payment.save(update_fields=['provider_reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0007_alter_product_image_alter_recipe_image'),
    ]

    operations = [
        migrations.RunPython(clear_duplicate_provider_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('method', 'provider_reference'), name='unique_provider_reference_per_method'),
        ),
    ]
