# Generated by Django 4.2 on 2025-05-23 21:18

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0007_alter_coupon_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legacy_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, help_text='Upload product image'),
        ),
    ]
