# Generated by Django 5.2.17 on 2026-09-04 12:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_recipe_order_items(apps, schema_editor):
    Order = apps.get_model('yummytummy_store', 'Order')
    RecipePurchase = apps.get_model('yummytummy_store', 'RecipePurchase')
    RecipeOrderItem = apps.get_model('yummytummy_store', 'RecipeOrderItem')

    order_ids = (
        RecipePurchase.objects.exclude(order_id=None)
        .order_by()
        .values_list('order_id', flat=True)
        .distinct()
    )
    for order in Order.objects.filter(pk__in=order_ids).iterator():
        purchases = list(
            RecipePurchase.objects.filter(order_id=order.pk)
            .select_related('recipe')
            .order_by('pk')
        )
        if not purchases:
            continue

        physical_total = sum(
            (item.price * item.quantity for item in order.items.all()),
            Decimal('0.00'),
        )
        target_total = max(order.subtotal_amount - physical_total, Decimal('0.00'))
        current_total = sum((purchase.recipe.price for purchase in purchases), Decimal('0.00'))
        allocated = Decimal('0.00')

        for index, purchase in enumerate(purchases):
            if index == len(purchases) - 1:
                price = target_total - allocated
            elif current_total > 0:
                price = (target_total * purchase.recipe.price / current_total).quantize(Decimal('0.01'))
                allocated += price
            else:
                price = Decimal('0.00')

            RecipeOrderItem.objects.get_or_create(
                order_id=order.pk,
                recipe_id=purchase.recipe_id,
                defaults={
                    'recipe_title': purchase.recipe.title,
                    'price': max(price, Decimal('0.00')),
                    'quantity': 1,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0008_payment_unique_provider_reference_per_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='yummytummy_store.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='yummytummy_store.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'recipe'), name='unique_recipe_per_order'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='recipe_order_item_price_nonnegative'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='recipe_order_item_quantity_positive')],
            },
        ),
        migrations.RunPython(backfill_recipe_order_items, migrations.RunPython.noop),
    ]
