# Generated by Django 5.2.17 on 2026-09-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0009_recipe_order_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationoutbox',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='recipeorderitem',
            options={'verbose_name': 'Recipe order line', 'verbose_name_plural': 'Recipe order lines'},
        ),
    ]
