# Generated by Django 5.2.17 on 2026-09-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0010_alter_notificationoutbox_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'permissions': [('view_owner_dashboard', 'Can view owner business dashboard')]},
        ),
        migrations.AddField(
            model_name='refund',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this refund was recorded as successful. Legacy refunds may be undated.', null=True),
        ),
    ]
