# Generated by Django 4.2 on 2025-06-12 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yummytummy_store', '0012_add_variant_field_to_orderitem'),
    ]

    operations = [
        # Add new fields to Order model
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User account (if account exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='auto_created_account',
            field=models.BooleanField(default=False, help_text='Whether an account was automatically created for this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='account_creation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the account creation email was sent'),
        ),
    ]
