# Generated by Django 4.2 on 2025-06-12 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yummytummy_store', '0013_add_order_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCreatedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_password_sent', models.BooleanField(default=False, help_text='Whether the initial password email was sent')),
                ('first_login_token', models.CharField(blank=True, help_text='Token for first-time login from email', max_length=64, null=True, unique=True)),
                ('token_expires', models.DateTimeField(blank=True, help_text='When the first-login token expires', null=True)),
                ('first_login_completed', models.BooleanField(default=False, help_text='Whether user has completed first login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('payment_confirmed', 'Payment Confirmed'), ('processing', 'Processing'), ('packaging', 'Packaging'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Additional details about this status update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Order Tracking Statuses',
                'ordering': ['-created_at'],
            },
        ),
        # Note: Skipping index renaming operations to avoid conflicts
        migrations.AddField(
            model_name='ordertrackingstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this status update', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertrackingstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_statuses', to='yummytummy_store.order'),
        ),
        migrations.AddField(
            model_name='autocreatedaccount',
            name='created_during_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_account_record', to='yummytummy_store.order'),
        ),
        migrations.AddField(
            model_name='autocreatedaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_created_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ordertrackingstatus',
            index=models.Index(fields=['order', '-created_at'], name='yummytummy__order_i_fe5752_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertrackingstatus',
            index=models.Index(fields=['status'], name='yummytummy__status_cd71a0_idx'),
        ),
        migrations.AddIndex(
            model_name='autocreatedaccount',
            index=models.Index(fields=['first_login_token'], name='yummytummy__first_l_9f0406_idx'),
        ),
        migrations.AddIndex(
            model_name='autocreatedaccount',
            index=models.Index(fields=['token_expires'], name='yummytummy__token_e_ed942d_idx'),
        ),
        migrations.AddIndex(
            model_name='autocreatedaccount',
            index=models.Index(fields=['-created_at'], name='yummytummy__created_ec13a3_idx'),
        ),
    ]
