# Generated by Django 4.2 on 2025-06-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0014_add_tracking_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='yummytummy__code_72d833_idx',
            old_name='maslove_sto_code_6da370_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='yummytummy__valid_f_db001b_idx',
            old_name='maslove_sto_valid_f_421a10_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='yummytummy__is_acti_07e166_idx',
            old_name='maslove_sto_is_acti_36cc54_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='yummytummy__created_5f751c_idx',
            old_name='yummytummy_sto_created_65181b_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='yummytummy__id_07ad7f_idx',
            old_name='maslove_sto_id_d55b8f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='yummytummy__name_162fe8_idx',
            old_name='maslove_sto_name_5c3190_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='yummytummy__created_d3e9cf_idx',
            old_name='maslove_sto_created_89cb43_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa STK Push Checkout Request ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa Merchant Request ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa Receipt Number', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_transaction_date',
            field=models.DateTimeField(blank=True, help_text='M-Pesa Transaction Date', null=True),
        ),
    ]
