# Generated by Django 4.2 on 2025-06-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummytummy_store', '0015_add_mpesa_fields'),
    ]

    operations = [
    ]
