# Generated by Django 4.2 on 2025-05-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maslove_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('bestseller', 'Bestseller'), ('seasonal', 'Seasonal'), ('limited_time', 'Limited Time'), ('new', 'New Arrival'), ('sale', 'On Sale')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
