# Generated by Django 4.2 on 2025-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maslove_store', '0004_coupon_order_discount_amount_order_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, help_text='Area/Neighborhood', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, help_text='Apartment/Building/House number', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='estate',
            field=models.CharField(blank=True, help_text='Estate/Community name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby recognizable location', max_length=150),
        ),
    ]
