# Generated by Django 4.2 on 2025-05-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maslove_store', '0005_order_area_order_building_order_estate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
