# Generated by Django 4.2 on 2025-05-23 21:18

from django.db import migrations
import os
import shutil


def copy_images_to_legacy(apps, schema_editor):
    """
    Copy existing images to the legacy_image field
    This ensures backward compatibility during the transition to Uploadcare
    """
    Product = apps.get_model('maslove_store', 'Product')

    # Get all products with images
    for product in Product.objects.all():
        # If the product has an image but no legacy image, copy it
        if product.image and not product.legacy_image:
            # The image field might be a string path from Uploadcare or a file path
            # We'll check if it's a file path and copy it to legacy_image
            if hasattr(product.image, 'path') and os.path.exists(product.image.path):
                product.legacy_image = product.image
                product.save()


def reverse_migration(apps, schema_editor):
    """
    No need to reverse this migration as it's just copying data
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('maslove_store', '0008_product_legacy_image_alter_product_image'),
    ]

    operations = [
        migrations.RunPython(copy_images_to_legacy, reverse_migration),
    ]
